PROJECT_PATH="$(pwd)" \
ACR_PATH="$PROJECT_PATH/auto-code-rover" \
SWE_AGENT_PATH="$PROJECT_PATH/SWE-agent" \
SWE_BENCH_PATH="$PROJECT_PATH/SWE-bench" \
MULTI_SWE_BENCH_PATH="$PROJECT_PATH/multi-swe-bench-env"
