name: swe-agent
dependencies:
  - python=3.11
  - pip
  - pip:
    - datasets
    - numpy
    - pandas
    - rich
    - ruamel.yaml
    - tenacity
    - unidiff
    - simple-parsing
    - rich-argparse
    - flask
    - flask-cors
    - flask-socketio
    - pydantic
    - python-dotenv
    - pydantic_settings
    - litellm
    - GitPython
    - ghapi
    - swe-rex>=1.2.0
    - tabulate
    - textual>=1.0.0
