name: 'AutoCodeRover'
description: 'Install AutoCodeRover dependencies.'

runs:

  using: 'composite'

  steps:

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', '${{ github.action_path }}') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install ACR dependencies
      id: install-deps
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
        echo "pip install ok"
        echo "ACR_PATH=${{ github.action_path }}" >> $GITHUB_OUTPUT
      shell: bash

outputs:
  ACR_PATH:
    description: "Path to AutoCodeRover source code directory."
    value: ${{ steps.install-deps.outputs.ACR_PATH }}